version: '3.8'

services:
  cstore-dev-db:
    container_name: cstore_dev_db
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=cstore
      - POSTGRES_PASSWORD=cstoresecret
      - POSTGRES_DB=cstore_dev_db
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cstore']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cstore-network

  cstore-api:
    container_name: cstore_api_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    depends_on:
      cstore-dev-db:
        condition: service_healthy
    environment:
      - .env
      # - DATABASE_URL=postgresql://cstore:cstoresecret@cstore-dev-db:5432/cstore_dev_db
      # - NODE_ENV=development
      # - JWT_SECRET=dev_jwt_secret
      # - JWT_AUTHENTICATE_SECRET="\/1N/\/\4RT-4UTH3NT1C4T3-4P1"
      # - JWT_AUTHENTICATE_OTP_SECRET="\/1N/\/\4RT-\/3R1FY-0TP-4P1"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cstore-network

volumes:
  postgres_dev:

networks:
  cstore-network:
    driver: bridge
