version: '3.8'

services:
  cstore-api:
    container_name: cstore_api_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - cstore-network

networks:
  cstore-network:
    driver: bridge
