version: '3.8'

services:
  cstore-dev-db:
    container_name: cstore_dev_db
    image: postgres:16-alpine
    env_file:
      - .env.dev
    ports:
      - 5434:5432
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    networks:
      - cstore-network

  cstore-api:
    container_name: cstore_api_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    depends_on:
      - cstore-dev-db
    env_file:
      - .env.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cstore-network

volumes:
  postgres_dev:

networks:
  cstore-network:
    driver: bridge
