version: '3.8'

services:
  cstore-prod-db:
    container_name: cstore_prod_db
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    networks:
      - cstore-network

  cstore-api:
    container_name: cstore_api_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - cstore-prod-db
    env_file:
      - .env
    networks:
      - cstore-network

volumes:
  postgres_prod:

networks:
  cstore-network:
    driver: bridge
