# Need this file for shut the service down
version: '3.8'

services:
  cstore-dev-db:
    extends:
      file: docker-compose.dev.yml
      service: cstore-dev-db

  cstore-api:
    extends:
      file: docker-compose.dev.yml
      service: cstore-api

volumes:
  postgres_dev:

networks:
  cstore-network:
    driver: bridge
