sequenceDiagram
    actor User
    participant C-Store
    participant API Server
    participant Database

    %% UPDATE password - successful case
    rect rgb(0, 128, 0, 0.1)
        Note right of User: Successful case - UPDATE password
        User->>C-Store: User access to update profile screen
        activate C-Store
        C-Store->>API Server: Request Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Header: { authorization }<br>Payload: { currentPassword, newPassword, confirmPassword }
        activate API Server
        API Server->>Database: Query "User" table by "id" attribute
        activate Database
        Database-->>API Server: Return user to compare old password
        API Server->>Database: Update new user's password with received value
        Database-->>API Server: Response success
        deactivate Database
        API Server-->>C-Store: [*] Update user's password success<br>Response<br>Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Status: 200<br>Payload: {}
        deactivate API Server
        C-Store-->>User: Redirect to Setting screen
        deactivate C-Store
    end

    %% UPDATE password - failure case 1: incorrect current password
    rect rgb(255, 0, 0, 0.1)
        Note right of User: Failure case 1 - Incorrect current password
        User->>C-Store: User access to update profile screen
        activate C-Store
        C-Store->>API Server: Request Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Header: { authorization }<br>Payload: { currentPassword, newPassword, confirmPassword }
        activate API Server
        API Server->>Database: Query "User" table by "id" attribute
        activate Database
        Database-->>API Server: Return user to compare old password
        deactivate Database
        API Server-->>C-Store: [*] Current password is incorrect<br>Response<br>Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Status: 400<br>Payload: { errors }
        deactivate API Server
        C-Store-->>User: Display Error Message<br>Message: The current password is incorrect.
        deactivate C-Store
    end

    %% UPDATE password - failure case 2: new password same as current
    rect rgb(255, 0, 0, 0.1)
        Note right of User: Failure case 2 - New password same as current
        User->>C-Store: User access to update profile screen
        activate C-Store
        C-Store->>API Server: Request Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Header: { authorization }<br>Payload: { currentPassword, newPassword, confirmPassword }
        activate API Server
        API Server-->>C-Store: [*] New password cannot be same as current password<br>Response<br>Method: PATCH<br>Endpoint: /api/v1/users/:userId/password/<br>Status: 400<br>Payload: { errors }
        deactivate API Server
        C-Store-->>User: Display Error Message<br>Message: New password cannot be same as current password
        deactivate C-Store
    end
