sequenceDiagram
    actor User
    participant C-Store
    participant APIServer
    participant EmailService
    participant Database

    rect rgba(0, 128, 0, 0.1)
        note right of User: Successful Case
        User->>C-Store: Enter Email
        activate C-Store
        C-Store->>APIServer: Request Method: POST<br>Endpoint: /api/v1/authentication/reset-password/<br>Payload: { email }
        activate APIServer
        APIServer->>Database: Query "User" table by "email" attribute
        activate Database
        Database-->>APIServer: Found record
        APIServer->>Database: Save new generated password for user
        Database-->>APIServer: Response success
        deactivate Database
        APIServer->>EmailService: Request to send new password to inputted email
        activate EmailService
        EmailService-->>APIServer: Response success

        par Asynchronous - Reset Password
            EmailService-->>User: Send "New Password" Email
        end

        deactivate EmailService
        APIServer-->>C-Store: [*] New password sent to email<br>Response<br>Method: POST<br>Endpoint: /api/v1/authentication/reset-password/<br>Status: 200<br>Payload: {}
        deactivate APIServer
        C-Store->>User: Redirect to Sign In screen
        deactivate C-Store
    end

    rect rgba(255, 0, 0, 0.1)
        note right of User: Failure Case
        User->>C-Store: Enter Email
        activate C-Store
        C-Store->>APIServer: Request Method: POST<br>Endpoint: /api/v1/authentication/reset-password/<br>Payload: { email }
        activate APIServer
        APIServer->>Database: Query "User" table by "email" attribute
        activate Database
        Database-->>APIServer: Cannot find by "email" attribute
        deactivate Database
        APIServer-->>C-Store: [*] Email is not registered<br>Response<br>Method: POST<br>Endpoint: /api/v1/authentication/reset-password/<br>Status: 400<br>Payload: { errors }
        deactivate APIServer
        C-Store-->>User: Display Error Message<br>Message: The email address you entered is not assigned to registered user.
        deactivate C-Store
    end
