sequenceDiagram
    actor User
    participant C-Store
    participant APIServer
    participant Database

    rect rgba(0, 128, 0, 0.1)
        note right of User: Successful Case
        User->>C-Store: User access to product detail screen
        activate C-Store
        C-Store->>APIServer: Request Method: GET<br>Endpoint: /api/v1/catalogue/products/:productId/<br>Header: { authorization }<br>Payload: {}
        activate APIServer
        APIServer->>Database: Query "Product" table joined with "Image" table<br>by "productId" attribute
        activate Database
        Database-->>APIServer: Return product included image
        deactivate Database
        APIServer-->>C-Store: [*] Get product success<br>Response<br>Method: GET<br>Endpoint: /api/v1/catalogue/products/:productId/<br>Status: 200<br>Payload: { id, categoryId, name, ... }
        deactivate APIServer
        C-Store-->>User: Render product to screen
        deactivate C-Store
    end

    rect rgba(255, 0, 0, 0.1)
        note right of User: Failure Case
        User->>C-Store: User access to product detail screen
        activate C-Store
        C-Store->>APIServer: Request Method: GET<br>Endpoint: /api/v1/catalogue/products/:productId/<br>Header: { authorization }<br>Payload: {}
        activate APIServer
        APIServer->>Database: Query "Product" table joined with "Image" table<br>by "productId" attribute
        activate Database
        Database-->>APIServer: Can not find "productId"
        deactivate Database
        APIServer-->>C-Store: [*] Endpoint is wrong or product deleted<br>Response<br>Method: GET<br>Endpoint: /api/v1/catalogue/products/:productId/<br>Status: 404<br>Payload: { errors }
        deactivate APIServer
        C-Store-->>User: Redirect to 404 not found screen
        deactivate C-Store
    end
